import { NextRequest, NextResponse } from "next/server";
import { generateRules } from "@/lib/rules";
import { createClient } from "@supabase/supabase-js";

const CDN = "https://designsync-omega.vercel.app";

function getSupabase() {
  return createClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!
  );
}

/**
 * GET /api/rules?ds=[slug]
 * Returns the DesignSync AI coding rules as plain text.
 */
export async function GET(request: NextRequest) {
  const dsSlug = request.nextUrl.searchParams.get("ds") || "";

  let fontFamily = "";
  let fontFamilyKo = "";
  let fontSansValue = "";
  let iconLibrary = "lucide";

  if (dsSlug) {
    // Slug provided → fetch from DB
    try {
      const { data } = await getSupabase()
        .from("design_systems")
        .select("tokens, icon_library")
        .eq("slug", dsSlug)
        .single();

      if (data) {
        fontFamily = data.tokens?.primitives?.fontFamily || "";
        fontFamilyKo = data.tokens?.primitives?.fontFamilyKo || "";
        iconLibrary = data.icon_library || "lucide";

        if (fontFamilyKo && fontFamily && fontFamily !== "Geist") {
          fontSansValue = `'${fontFamily}', '${fontFamilyKo}', sans-serif`;
        } else if (fontFamilyKo) {
          fontSansValue = `'${fontFamilyKo}', sans-serif`;
        } else if (fontFamily && fontFamily !== "Geist") {
          fontSansValue = `'${fontFamily}', sans-serif`;
        }
      }
    } catch {
      // Continue with defaults
    }
  } else {
    // No slug → fallback to static tokens
    try {
      const res = await fetch(`${CDN}/r/designsync-tokens.json`, {
        next: { revalidate: 0 },
      });
      if (res.ok) {
        const tokens = await res.json();
        fontSansValue = tokens?.cssVars?.light?.["font-sans"] || "";
        if (fontSansValue) {
          const families = fontSansValue
            .split(",")
            .map((s: string) => s.trim().replace(/^'|'$/g, ""))
            .filter((s: string) => s && s !== "sans-serif");
          fontFamily = families[0] || "";
          fontFamilyKo = families[1] || "";
        }
      }
    } catch {
      // Continue with defaults
    }
  }

  const rules = generateRules({
    fontFamily,
    fontFamilyKo,
    fontSansValue,
    iconLibrary,
    includeInstall: false,
  });

  const header = `# DesignSync — AI Coding Rules
# Generated by DesignSync (${CDN})
${dsSlug ? `# Design System: ${dsSlug}\n` : ""}# This file is auto-generated. Re-run the setup command to update.

`;

  return new NextResponse(header + rules, {
    headers: {
      "Content-Type": "text/plain; charset=utf-8",
      "Cache-Control": "no-cache, no-store, must-revalidate",
      "Access-Control-Allow-Origin": "*",
    },
  });
}
