import { NextResponse } from "next/server";
import { generateRules } from "@/lib/rules";

const CDN = "https://designsync-omega.vercel.app";

/**
 * GET /api/rules
 * Returns the DesignSync AI coding rules as plain text.
 * The setup script fetches this to write .cursorrules and CLAUDE.md.
 */
export async function GET() {
  // Fetch the latest tokens from CDN to extract font info
  let fontFamily = "";
  let fontFamilyKo = "";
  let fontSansValue = "";

  try {
    const res = await fetch(`${CDN}/r/designsync-tokens.json`, {
      next: { revalidate: 0 },
    });
    if (res.ok) {
      const tokens = await res.json();
      fontSansValue = tokens?.cssVars?.light?.["font-sans"] || "";
      // Try to extract font family names from the font-sans value
      // e.g. "'Poppins', 'Pretendard', sans-serif" → Poppins, Pretendard
      if (fontSansValue) {
        const families = fontSansValue
          .split(",")
          .map((s: string) => s.trim().replace(/^'|'$/g, ""))
          .filter((s: string) => s && s !== "sans-serif");
        fontFamily = families[0] || "";
        fontFamilyKo = families[1] || "";
      }
    }
  } catch {
    // Continue with defaults if fetch fails
  }

  const rules = generateRules({
    fontFamily,
    fontFamilyKo,
    fontSansValue,
    includeInstall: false,
  });

  const header = `# DesignSync — AI Coding Rules
# Generated by DesignSync (${CDN})
# This file is auto-generated. Re-run the setup command to update.

`;

  return new NextResponse(header + rules, {
    headers: {
      "Content-Type": "text/plain; charset=utf-8",
      "Cache-Control": "no-cache, no-store, must-revalidate",
      "Access-Control-Allow-Origin": "*",
    },
  });
}
